image: skmedia/bitbucket-pipelines-php80:latest

common: &common
  step:
    name: App Build
    caches:
      - composer
    script:
      - service mysql start
      - mysql -h localhost --user=root --password=root -e "CREATE DATABASE focus;"
      - mysql -h localhost --user=root --password=root -e "GRANT USAGE ON *.* TO homestead@localhost IDENTIFIED BY 'secret';"
      - mysql -h localhost --user=root --password=root -e "GRANT ALL PRIVILEGES ON test.* TO homestead@localhost;"
      - mysql -h localhost --user=root --password=root -e "FLUSH PRIVILEGES;"
      - composer --version
      - composer install
      - php artisan migrate -y
      - composer global require phpunit/phpunit
      - PATH="~/.composer/vendor/bin:$PATH"
      - phpunit --version
      - phpunit

pipelines:

  branches:
    master:
      - <<: *common
      - step:
          name: Deploy to master
          deployment: Production
          script:
            - apt-get update && apt-get install -y unzip wget
            - wget -q --spider https://forge.laravel.com/servers/466621/sites/1342660/deploy/http?token=x7H4snM7g0jFIqBi2Ob0nETwJLYoLuFaodU4NicG
    dev:
      - <<: *common
      - step:
          name: Deploy to development
          script:
            - apt-get update && apt-get install -y unzip wget
            - wget -q --spider https://forge.laravel.com/servers/454109/sites/1354396/deploy/http?token=IgQr1SbYEOjWDl8aVcbEqotX3Dw3poKJfRJKrwFQ

definitions:
  services:
    mysql:
      image: mysql:8.0
      variables:
        MYSQL_DATABASE: 'focus_testing'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'test_user'
        MYSQL_PASSWORD: 'test_user_password'
