version: "3.8"

services:

  mysql:
    container_name: laravel_mysql
    build:
      context: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: focus
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass
    ports:
      - "9906:3306"
    volumes:
      - .:/var/lib/db/mysql

  php:
    container_name: laravel_php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/api-focus
    links:
      - mysql

  nginx:
    container_name: laravel_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/api-focus
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
